### PR TITLE
fixes path in Nomad deploy

### PR DESCRIPTION
**Pull request by nustiueudinastea**
- path and name of files has changed a while ago

### CODE REVIEW

**Comment by vlal-zz** [comment]
@nustiueudinastea we can probably just delete these lines as the deploy_doc for nomad uses the healthcheck container on docker hub

**Comment by nustiueudinastea** [comment]
@vlal even better. Will make the change.

**Comment by nustiueudinastea** [comment]
@vlal done

**Review by vlal-zz — APPROVED** [review]
lgtm

**Pull request merged**
