### PR TITLE
Remove namespace object and all zipkin objects

### LINKED ISSUE #3214: Issue with /docs/getting-started-guides/kubeadm/
**This is a...** 

- [ ] Feature Request
- [X] Bug Report

**Problem:**
The command to create the sock-shop application error out (it's also not necessary to create the `sock-shop` namespace beforehand as that is already define in `complete-demo.yaml`):

```
# kubectl create namespace sock-shop
namespace "sock-shop" created

# kubectl apply -n sock-shop -f "https://github.com/microservices-demo/microservices-demo/blob/master/deploy/kubernetes/complete-demo.yaml?raw=true"
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
namespace "sock-shop" configured
namespace "zipkin" created
deployment "carts-db" created
service "carts-db" created
deployment "carts" created
service "carts" created
deployment "catalogue-db" created
service "catalogue-db" created
deployment "catalogue" created
service "catalogue" created
deployment "front-end" created
service "front-end" created
deployment "orders-db" created
service "orders-db" created
deployment "orders" created
service "orders" created
deployment "payment" created
service "payment" created
deployment "queue-master" created
service "queue-master" created
deployment "rabbitmq" created
service "rabbitmq" created
deployment "shipping" created
service "shipping" created
deployment "user-db" created
service "user-db" created
deployment "user" created
service "user" created
the namespace from the provided object "zipkin" does not match the namespace "sock-shop". You must pass '--namespace=zipkin' to perform this operation.
the namespace from the provided object "zipkin" does not match the namespace "sock-shop". You must pass '--namespace=zipkin' to perform this operation.
the namespace from the provided object "zipkin" does not match the namespace "sock-shop". You must pass '--namespace=zipkin' to perform this operation.
the namespace from the provided object "zipkin" does not match the namespace "sock-shop". You must pass '--namespace=zipkin' to perform this operation.
the namespace from the provided object "zipkin" does not match the namespace "sock-shop". You must pass '--namespace=zipkin' to perform this operation.
```

**Proposed Solution:**
Change the command to: `kubectl create -f "https://github.com/microservices-demo/microservices-demo/blob/master/deploy/kubernetes/complete-demo.yaml?raw=true"`

```
# kubectl create -f "https://github.com/microservices-demo/microservices-demo/blob/master/deploy/kubernetes/complete-demo.yaml?raw=true"
namespace "sock-shop" created
namespace "zipkin" created
deployment "carts-db" created
service "carts-db" created
deployment "carts" created
service "carts" created
deployment "catalogue-db" created
service "catalogue-db" created
deployment "catalogue" created
service "catalogue" created
deployment "front-end" created
service "front-end" created
deployment "orders-db" created
service "orders-db" created
deployment "orders" created
service "orders" created
deployment "payment" created
service "payment" created
deployment "queue-master" created
service "queue-master" created
deployment "rabbitmq" created
service "rabbitmq" created
deployment "shipping" created
service "shipping" created
deployment "user-db" created
service "user-db" created
deployment "user" created
service "user" created
deployment "zipkin" created
service "zipkin" created
deployment "zipkin-mysql" created
service "zipkin-mysql" created
deployment "zipkin-cron" created
```

**Page to Update:**
https://kubernetes.io/docs/getting-started-guides/kubeadm/#optional-installing-a-sample-application

Kubernetes Version: 1.6.1

### PR DESCRIPTION
**Pull request by errordeveloper**
fix kubernetes/kubernetes.github.io#3214

### CODE REVIEW

**Comment by vlal-zz** [comment]
@errordeveloper you've got conflicts

**Comment by errordeveloper** [comment]
@vlal fixed now :)

**Comment by vlal-zz** [comment]
some of the other services such as carts, orders, shipping also make reference to ZIPKIN. I'm thinking these should be removed as well.

**Comment by jasonrichardsmith** [comment]
Closing consolidating under #727

**Pull request closed without merging**
