### PR TITLE
add k8s namespace

### PR DESCRIPTION
**Pull request by RaphaelHerd**
add k8s namespace. Otherwise the yaml file is not usable as complete demo by just deploying this file

### CODE REVIEW

**Review by pidster — COMMENTED** [review]
I think we've been around this loop a couple of times. 
IIRC the namespace is specified when applying the file.

**Comment by mongrelion** [comment]
@pidster I think that @RaphaelHerd is referring to the `complete-demo.yaml` file, which indeed does not feature the definition of the namespace, making the deployment fail when starting from the scratch. A quick workaround is to actually create the namespace by hand with `kubectl create namespace sock-shop`.

However, I would like to mention here that in the past we have expressed the intention to get rid of the `complete-demo.yaml` and just stick to the `manifests/` folder, which, indeed, includes the right manifest for creating the *sock-shop* namespace.

**Comment by pidster** [comment]
> we have expressed the intention to get rid of the complete-demo.yaml

People keep suggesting this and we keep saying "no".

**Comment by embs** [comment]
I'm sorry for having created a PR with this very same addition. I wasn't aware of this one.

> get rid of the `complete-demo.yaml` and just stick to the `manifests/`

This would be unfortunate for me as I wasn't able to deploy the Sock Shop on minikube with the `manifests/` (have faced errors like [this](https://github.com/microservices-demo/microservices-demo/issues/729#issuecomment-318249437) and [this](https://github.com/microservices-demo/microservices-demo/issues/717#issuecomment-308067148)) but it works with the complete-demo (with the addition of the namespace).

For the record: this PR closes #733.

**Comment by RaphaelHerd** [comment]
Yes of course I can add it manually but my understanding of "complete" is complete without editing some lines otherwise it's not usable. I used your demo several times a day to validate our cluster and this is simply not practical. Yes I can fork your repo but my intension is to give you feedback.

So accept the request and it should work in any case......

**Comment by mongrelion** [comment]
@pidster fair enough. I've been checking the docs, though, and nowhere do we mention the manual creation of the namespace, so I think that this PR is a good idea.
Unless you have anything to add or any opposition I'd like to ahead and merge this.

**Comment by pidster** [comment]
The Kubernetes docs manage to include the correct instructions:
https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm/#optional-installing-a-sample-application

**Comment by pidster** [comment]
@mongrelion If this change breaks the Kubernetes docs, either those need changing at the _same time_, or the docs on our site need changing instead.

**Review by etiennetremel — APPROVED** [review]

**Comment by etiennetremel** [comment]
https://github.com/microservices-demo/microservices-demo/issues/746

**Pull request closed without merging**
