### PR TITLE
Update Grafana graphics

### PR DESCRIPTION
**Pull request by mongrelion**
This pull request updates the graphics that we support in Grafana

### Graphs for the Docker Compose Deployment
I have added some configuration files and a script for setting up Grafana, Prometheus and some graphs for the deployment done with Docker Compose. This can also be used for the deployment done with Docker Swarm (with and without Weave).

### The RED method
I have split down the graphs that we originally had in the Sock Shop Performance Dashboard into smaller chunks to follow the RED method define in [this article](https://www.weave.works/blog/the-red-method-key-metrics-for-microservices-architecture/).

Here's a preview of the changes:

zwu35

There are three more like these for the rest of the services.

### CODE REVIEW

**Comment by errordeveloper** [comment]
By the way, have you looked at https://github.com/weaveworks/grafanalib?

**Comment by errordeveloper** [comment]
Overall, LGTM.

**Comment by errordeveloper** [comment]
The screenshot shows 3 services, but there are 6 in [`prometheus.yaml`](https://github.com/microservices-demo/microservices-demo/blob/23a02ec3720c47f1168962f0afc1740031fa5d9f/deploy/docker-compose/prometheus.yml). 
Are the other 3 present on the dashboard but simply not included in the screenshot?

Also, I think front-end was also instrumented for prom, wasn't it?

**Comment by mongrelion** [comment]
@errordeveloper there are indeed 6 services in the dashboard. The screenshot only shows 3, though.

Also, good catch! the frontend indeed has an endpoint for metrics but it's not being scratched yet. I'm going to update the PR accordingly!

Cheers!

**Comment by mongrelion** [comment]
@errordeveloper I just added the front-end graphs to the Grafana Dashboard. Pretty much like the other ones.
Should I go ahead and merge this?

**Comment by errordeveloper** [comment]
> Should I go ahead and merge this?

It'd be nice to use grafanalib.

**Comment by mongrelion** [comment]
> It'd be nice to use grafanalib.

I propose that we get this through since there are quite some changes already introduced (REDify graphs by splitting them down into smaller graphs *and* adding frontend graphs to the dashboard) and in the next PR we migrate to grafanalib.

How does that sound?

**Comment by mongrelion** [comment]
@errordeveloper also, now that we're at it: what would be the idea for deployment with grafanalib? do we include the resulting output from grafanalib into the repo or we generate the JSON on the fly when importing the graphs?

**Review by vlal-zz — APPROVED** [review]
LGTM

**Pull request merged**
