### PR TITLE
Staging add flux

### PR DESCRIPTION
**Pull request by vlal-zz**
* Update README
* Add fluxctl automation script
* Update terraform to install flux svc,dep

### CODE REVIEW

**Comment by vlal-zz** [comment]
@pidster need to add bastion secret key to the github repo. Could I get access?

**Comment by vlal-zz** [comment]
ping @pidster

**Comment by pidster** [comment]
Why do we need the bastion key here?

**Comment by vlal-zz** [comment]
I don't think it necessarily needs to be the bastion key. But I believe flux requires a key here and in it's config?

**Comment by pidster** [comment]
Ahh... is this a standalone Flux?

**Comment by pidster** [comment]
It is.

**Comment by vlal-zz** [comment]
doesn't hosted flux also require the key to be uploaded?

**Comment by vlal-zz** [comment]
@pidster ready for review

**Review by pidster — APPROVED** [review]

**Pull request merged**
