### PR TITLE
add zipkin namespace

### LINKED ISSUE #630: Use specific namespace for Zipkin in Kubernetes deployments
The current configuration applies Zipkin in the same namespace, cluttering views.

Change the namespace to a unique one for Zipkin.

### PR DESCRIPTION
**Pull request by vlal-zz**
* Move zipkin to it's own namespace

Fixes #630

### CODE REVIEW

**Review by nustiueudinastea — APPROVED** [review]
lgtm

**Comment by vlal-zz** [comment]
Hi @rgtoronto 
We split things into namespaces as means to be more ogranized, since zipkin is an optional component we've moved it into it's own namespace to avoid cluttering the sock-shop namespace. You can read more about namespaces [here](https://kubernetes.io/docs/user-guide/namespaces/). 
You should be fine deploying the sock shop app into one namespace. If you have further questions a better way to reach use is through our slack channel located [here](https://weaveworks.github.io/community-slack/) 

Cheers,

**Comment by rgtoronto** [comment]
@vlal Thanks for reply. one namespace works!
one more question: since currently all the service names are hard coded and unique,  will sockshop app keep working if we modify the service name to different ones? i.e. cart change to first-cart? so we could run multiple instances of sockshop on k8s?

**Comment by vlal-zz** [comment]
No worries. Glad to hear!
@rgtoronto You're better off taking this question to the public slack channel located [here](https://weaveworks.github.io/community-slack/).

**Pull request merged**
