### PR TITLE
updated currency

### LINKED ISSUE #78: Switch £ to $

### PR DESCRIPTION
**Pull request by jasonrichardsmith**
fixes #78

### CODE REVIEW

**Comment by philwinder** [comment]
@jasonrichardsmith Can you re-merge in master. There was a bug in the travis script that prevented your branch from passing the build tests.

**Comment by jasonrichardsmith** [comment]
closed to rerun

**Comment by philwinder** [comment]
See https://github.com/weaveworks/weaveDemo/pull/79#issuecomment-227391906

**Comment by philwinder** [comment]
Wooh! Finally. Thanks for your help @jasonrichardsmith

**Pull request merged**
