### PR TITLE
Add ALB for scope

### LINKED ISSUE #416: ECS CloudFormation: the WeaveScope output shouldn't be loadbalanced
The WeaveScope output goes through an ELB:

screen shot 2016-11-17 at 12 42 47

This is wrong since it leads to a split brain in the apps, affecting things like terminal spawning:

See: https://github.com/weaveworks/scope/issues/2016#issuecomment-261226026
Identical issue for the integrations repository: https://github.com/weaveworks/integrations/issues/115

### PR DESCRIPTION
**Pull request by vlal-zz**
* Add a Application Load Balancer for Weave Scope to the CloudFormation.

Fixes #416

### CODE REVIEW

**Comment by vlal-zz** [comment]
@errordeveloper @2opremio Does this solve the split-brain issue? The ALB has support for WebSockets which I believe was causing the issue with the other LoadBalancer.

**Comment by 2opremio** [comment]
>  Does this solve the split-brain issue? 

I haven't used ALBs so I can't tell. have you tested it?

**Comment by vlal-zz** [comment]
I briefly tested it and Scope seemed to be running fine. But I'd be happy if someone with more Scope experience could take it for a spin.

**Comment by 2opremio** [comment]
Did terminals work?

**Comment by vlal-zz** [comment]
attach worked but I never tested exec, I presume since attach worked exec would have as well. But I'd be happy to make sure if you have doubts.

**Comment by 2opremio** [comment]
If terminals work consistently (test at least 10 times both attach and
exec) then I think it should be fine.

**Comment by vlal-zz** [comment]
Unfortunately I wasn't able to consistently exec into a container from the ALB url, but from any instance URL I was.

**Pull request closed without merging**
