### PR TITLE
Tidy up script.

### PR DESCRIPTION
**Pull request by amouat**
- Read the contribution guidelines
- Include a reference to a related issue in this repository
- A description of the changes proposed in the pull request
  - Replace exit_on_failure calls with set -e
  - Add set -o pipefail for extra checks
  - minify cleanup function
  - remove redundant reschedule env var (wrong version of swarm!)

### CODE REVIEW

**Review by pidster — APPROVED** [review]

**Comment by pidster** [comment]
@amouat can you rebase this please?

**Comment by amouat** [comment]
Snuck in some docs at the same time, which may be bad form.

**Comment by pidster** [comment]
@amouat Can you please rebase this PR?

**Comment by amouat** [comment]
Rebased - sorry about delay; conferences then holiday got in the way.

**Pull request merged**
