### PR TITLE
Local prometheus and alertmanager

### PR DESCRIPTION
**Pull request by nustiueudinastea**
This PR adds a prometheus + alertmanager to the k8s deployment.

### CODE REVIEW

**Comment by rade** [comment]
> This PR adds a prometheus + alertmanager to the k8s deployment.

Why? Is there an issue describing what problem we are trying to solve here?

cc @lukemarsden

**Comment by lukemarsden** [comment]
Hey Alex, what's the context here?

**Comment by nustiueudinastea** [comment]
@rade @lukemarsden it is related to https://github.com/microservices-demo/microservices-demo/issues/422. Wanted to add some alerting but Weave's cloud alerting is not ready yet, so we added a local instance of alert manager + prometheus. The metrics for the front-end have already been improved and I think they are satisfactory now.

**Review by philwinder — CHANGES_REQUESTED** [review]
Request that you put the api url in a k8s secret.
And squash all those commits.

**Review by philwinder — APPROVED** [review]
One last thing. Could you add a `.../manifests-alerting/README.md` to note that you need an environmental variable called `API_URL_SECRET` to use the slack stuff.
Thanks.

**Pull request merged**
