### PR TITLE
(WIP) Add circle.yml

### PR DESCRIPTION
**Pull request by sashkachan**
Currently testing only go services.
Needs a better structure.

### CODE REVIEW

**Comment by philwinder** [comment]
:+1:
But we need to think how we're going to use the different services. E.g. what is circle doing, what is travis doing, etc. Does it make sense to have different builders? Can it help?
Have a think.

**Comment by sashkachan** [comment]
@philwinder @idcrosby It really doesn't make sense to use multiple build systems, unless we want to show it as a reference how to?

I don't find circleci to be better or worse than travis, both are pretty plain and easy to implement.
Most of the juice will be in sub-projects test directories, the build yaml files only used to bootstrap testing and check the results, really.

**Comment by pidster** [comment]
We could use Travis to build 'Sock Shop' & Circle to build 'Micro Sock Shop'.

**Comment by sashkachan** [comment]
Close for now until we decide if we'll use Circle at any point.

**Pull request closed without merging**
