### PR TITLE
Temporary edits for minikube instructions

### PR DESCRIPTION
**Pull request by philwinder**
- Read the contribution guidelines
- Include a reference to a related issue in this repository
- A description of the changes proposed in the pull request

### CODE REVIEW

**Review by vlal-zz — APPROVED** [review]

**Comment by philwinder** [comment]
This wasn't meant to be merged. But oh well. Will be fixed in #360

**Comment by rade** [comment]
> This wasn't meant to be merged

How was anyone meant to know that?

**Comment by philwinder** [comment]
Chill out @rade, no need to be aggressive. No harm done. I needed some way of my class to be able to see some working instructions. This was the quickest way to do it in the 2 minutes I had to do it.

I put the words temp in there and I was going to delete it when I got home. But didn't do it in time.

**Comment by rade** [comment]
No aggression was intended.

In other repos we are adding a '[WIP]' prefix to indicate stuff that shouldn't be merged. Also, assigning to yourself will usually keep others at bay.

**Pull request merged**
