### PR TITLE
Deploy docs k8s flux

### LINKED ISSUE #434: Deploy docs for kubernetes should take advantage of Weave Flux
- [x] Create terraform files to create a cluster of 3+ instances 
   - [x] Setup kubernetes on the cluster

Ssh into the master node
- [x] Setup Weave net on master node
- [x] Install and setup Weave scope
- [x] Install fluxd on master node
- [x] Install fluxctl on master node
- [x] Integrate slack
- [x] Create and populate flux.conf file
- [x] Deploy sockshop
- [x] Set fluxctl automate 

References
* https://www.weave.works/guides/cloud-guide-part-2-deploy-continuous-delivery/

### PR DESCRIPTION
**Pull request by vlal-zz**
* Deploy docs k8 + flux
* Added encrypted file from travis for use with flux
* Added slack webhook for sock-shop channel
* To force this deploy doc to redeploy you need to delete the key in aws otherwise only the healthchecks are run

- [ ] Add public key to this repo
- [ ] Delete public key locally

Fixes #434 #459 #458 #360

### CODE REVIEW

**Comment by vlal-zz** [comment]
@pidster adding the public key to the repo is the only outstanding issue remaining. Unless you want the fluxctl part to be seperated and done manually?

**Comment by vlal-zz** [comment]
@pidster what's the plan for this PR?

**Comment by vlal-zz** [comment]
In hindsight this seems more complicated than it should be. I'm going to change things a bit and simplify things.

**Comment by nustiueudinastea** [comment]
@vlal what is the plan for doing the k8s deployment with flux? If you are still working on integrating flux, please try to change the k8s image versions to "latest" and see if that works. This would be an improvement that helps to reduce problems like this: https://github.com/microservices-demo/microservices-demo/issues/443

**Comment by pidster** [comment]
Flux wants to operate on its own GitHub repo when it makes changes. This should probably be a clone of the main one, not self-referential.

**Pull request closed without merging**
