### PR TITLE
Migrate to deploy_doc gem

### PR DESCRIPTION
**Pull request by vlal-zz**
* Changes related to using the deploy_doc gem

### CODE REVIEW

**Comment by ttrahan** [comment]
@vlal the find/replace on 'test' made unintended changes (see ecs-weave-shippable.md). Should run the find/replace on 'deploy-test' instead

**Comment by vlal-zz** [comment]
oh you're right! apologies for that I'll change it back.

**Comment by vlal-zz** [comment]
should be good now

**Comment by ttrahan** [comment]
thanks

**Review by pidster — APPROVED** [review]

**Pull request merged**
