### PR TITLE
Optimise builds

### PR DESCRIPTION
**Pull request by idcrosby**
For Go services, created builder images and minimal 'release' images. Switched to an alpine node image (not official) and updated travis script.

### CODE REVIEW

**Comment by rade** [comment]
Any comparative data to https://github.com/weaveworks/microservices-demo/issues/128#issuecomment-233052890?

**Comment by idcrosby** [comment]
```
REPOSITORY                  TAG                 IMAGE ID            CREATED              SIZE
weaveworksdemos/login       latest              985af36f2a4a        23 seconds ago       8.875 MB
weaveworksdemos/catalogue   latest              dee2931e5d73        About a minute ago   19.1 MB
weaveworksdemos/front-end   latest              4a898c732362        2 minutes ago        78 MB
weaveworksdemos/payment     latest              caaf99fb5cf2        2 minutes ago        8.777 MB
```

**Comment by rade** [comment]
nice. what about the others?

**Comment by idcrosby** [comment]
Leaving the java images as is, they are using alpine and will not get much smaller.
Will work on the python image, but it is less important since it is not part of the actual application.

**Comment by pidster** [comment]
LGTM.

**Pull request merged**
