### PR TITLE
tooks tags to calculate catalog size

### LINKED ISSUE #31: When filtering, size, paging and page sizing returns incorrect values.
We get the total data size from the backend. When filtering, this is obviously wrong.

### PR DESCRIPTION
**Pull request by jasonrichardsmith**
resolves #31 
passes tags to service to filter catalog prior to returning length

### CODE REVIEW

**Comment by philwinder** [comment]
Thanks @jasonrichardsmith. I'll just test this.

**Comment by philwinder** [comment]
@jasonrichardsmith Can you re-merge in master. There was a bug in the travis script that prevented your branch from passing the build tests.

**Comment by jasonrichardsmith** [comment]
The build failed with this error:
Tag openjdk-8-alpine not found in repository docker.io/library/java

But it passed on other tests

**Comment by jasonrichardsmith** [comment]
reopening to attempt test again

**Comment by philwinder** [comment]
@jasonrichardsmith Be wary of docker errors. Docker hub is very temperamental. It might be nothing.

**Comment by jasonrichardsmith** [comment]
So at this point it looks they are failing to push.
@philwinder

**Comment by philwinder** [comment]
wtf. An error logging in:

```
$ docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
flag needs an argument: -p
See 'docker login --help'.
```

I'll debug. Thanks.

**Comment by philwinder** [comment]
@jasonrichardsmith: I have no idea. With exactly the same code it works in master:

```
0.59s$ docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
WARNING: login credentials saved in /home/travis/.docker/config.json
Login Succeeded
```

I'll continue to try and fix tomorrow. Sorry.

**Comment by philwinder** [comment]
@jasonrichardsmith: I've figured out the problem. The issue was that Travis does not share it's secure variables (e.g. passwords) with untrusted PRs. Because you're PR is coming from your repo, it wouldn't let you see the docker hub password.

So, I've added some code to check whether it is trusted or not. If not, skip the docker push.

So, can you (again!) merge master and try again. Thanks!

**Comment by jasonrichardsmith** [comment]
No problem!  Will do over lunch

**Pull request merged**
