### PR TITLE
Fixes #416 Scope moved to a seperate elb

### LINKED ISSUE #416: ECS CloudFormation: the WeaveScope output shouldn't be loadbalanced
The WeaveScope output goes through an ELB:

screen shot 2016-11-17 at 12 42 47

This is wrong since it leads to a split brain in the apps, affecting things like terminal spawning:

See: https://github.com/weaveworks/scope/issues/2016#issuecomment-261226026
Identical issue for the integrations repository: https://github.com/weaveworks/integrations/issues/115

### PR DESCRIPTION
**Pull request by vlal-zz**
* Fixed #416 Move Scope to a seperate ELB

### CODE REVIEW

**Comment by pidster** [comment]
Can either @errordeveloper or @2opremio do a review please?

**Comment by errordeveloper** [comment]
@vlal could you please elaborate on how this fixes #416?

**Comment by vlal-zz** [comment]
Judging by the issue the idea was to remove WeaveScope off the original load balancer, but the discussion here weaveworks/integrations#115 mentioned running one app behind the load balancer, and the original reason for the load balancer being the URL listed in the outputs section of CloudFormation stack status page. So I figured putting each app behind their own load balancer would solve the split brain and allow the url to be displayed in the status page.

**Comment by errordeveloper** [comment]
I think you may be missing one detail here, when we talk about 'app' in
this case, we mean the UI part of Scope... Sorry if this is a bit
confusing. Anyhow, I am going to try sticky sessions for Scope app, and I
am not sure if that would require a separate ELB, so I might need to merge
this first :)

**Comment by vlal-zz** [comment]
Oops, cool no worries I'll leave this open just in case

**Pull request closed without merging**
