### PR TITLE
Refactor catalogue service with Go kit

### PR DESCRIPTION
**Pull request by peterbourgon**
I tried to break up the commits in some sane order. Roughly,
1. Define a Go interface for the service
2. Implement core business logic, agnostic of transport
3. Write (admittedly tedious) endpoint bindings
4. Implement transport bindings, i.e. gorilla/mux HTTP
5. Write middleware for value-add stuff, initially just logging, more later
6. Write cmd/cataloguesvc to wire everything together
7. Fix a few bugs

Don't merge this until we get a chance to chat! :)

### CODE REVIEW

**Comment by peterbourgon** [comment]
I come from the author-merges tribe, so give me a LGTM and I'll merge this. Or, if you like to work another way in this repo, just let me know.

**Comment by philwinder** [comment]
That's fine, so long as you've tested that everything works. We're not focusing on the application at the moment, so I haven't had time.

**Comment by peterbourgon** [comment]
The tests are green. Is there more testing to do?

**Comment by philwinder** [comment]
Ha, tests. You're funny. Guess how many tests there were after two weeks of writing 10 microservices? No it's all manual testing. I.e. go onto the site and start ordering and viewing, etc.

**Comment by idcrosby** [comment]
We do actually have the load/integration tests (/load-test/). They are not hooked in to the build yet, but should be usable to validate the functionality is still working.

**Comment by peterbourgon** [comment]
Clicking around works now. Merging!

**Pull request merged**
