### PR TITLE
Add CloudFormation template and enable publishing from Travis

### PR DESCRIPTION
**Pull request by errordeveloper**
I've also unfolded some long lines in `.travis.yml.

Two secretes where added via Travis config UI:
- `AWS_ACCESS_KEY_ID`
- `AWS_SECRET_ACCESS_KEY`

### CODE REVIEW

**Review by pidster — APPROVED** [review]

**Comment by errordeveloper** [comment]
@pidster I'm testing publishing on another branch right now, will merged once confirmed it works.

**Comment by pidster** [comment]
Will this address: https://github.com/microservices-demo/microservices-demo/issues/296?

**Comment by errordeveloper** [comment]
Ok, all is well, here is the new published template: https://s3.amazonaws.com/weaveworks-cfn-public/microservices-demo/microservices-demo.json

@pidster I'll remove it from integrations repo now. One question - I don't see a point of having a bash implementation around (`deploy/aws-ecs/{setup,cleanup}.sh` and friends), WDYT?

Well, one could stay that users who don't know CloudFormation should be able to read bash code, but it's a duplicate of what we have in the integrations repo as well, and I don't know why would we want to maintain so many implementations things.

**Comment by errordeveloper** [comment]
> Will this address: #296?

Not as is. I can make another PR for that.

**Comment by errordeveloper** [comment]
I just force pushed (as it turned out I added old version of `cloudformation.json` that I had locally), but Github doesn't require another review after a force push (something to beware of).

**Comment by errordeveloper** [comment]
Ok, I've also added users DB and service, which should fix #296.

**Comment by errordeveloper** [comment]
I'm gonna test it end-to-end now to be sure #296 is fixed.

**Comment by errordeveloper** [comment]
Turns out this still wasn't up to-date, I've added catalogue DB and hope it will fix it, re-testing. The bash implementation is also out of date, @pidster do you mind we get rid of it?

**Comment by errordeveloper** [comment]
@pidster this is working end-to-end now.

**Pull request merged**
