### PR TITLE
Avoid granting Linux capabilities

### PR DESCRIPTION
**Pull request by shiresky**
My task was to run your Helm chart on K8s cluster with restrictive pod security policy. The worst problem I encountered was that you grant Linux capabilities in order to bind 80 port inside of container. As a result I was not able to run these images in any way without rebuilding them reverting this operation. That's why I propose you to use other port inside of containers and map it externally to 80 during running a container.
My second issue I resolve with this commit is introducing support of custom Docker registry. On my environment I do not have direct Internet access and need to prefix images with registry address to be able to download them.
I also increased initial delay values for probes at 2 deployments because on my environment these pods need more time to got up and too early starting checking readiness caused with continuosly restarting these pods.

### CODE REVIEW

**Comment by CsatariGergely** [comment]
@dholbach can you please review?

**Comment by CsatariGergely** [comment]
> 
> 
> @dholbach can you please review?

Or maybe @rndstr ?

**Comment by CsatariGergely** [comment]
> 
> 
> > @dholbach can you please review?
> 
> Or maybe @rndstr ?

Or maybe @Ottovsky ? Thanks.

**Comment by CsatariGergely** [comment]
@rndstr , @dholbach can you please help me to find the right persons who could review this pr?

**Comment by rodrmartinez** [comment]
@shiresky please update the Deployments templates with the new apiversion, this has already been fixed on the last merge. Also I would suggest to set the port numbers in values.yaml and use 80 as default, then modify the templates to not add the capabilities section if a different port is used, this way it will be consistent with the other supported deployment methods.

**Pull request closed without merging**
