### PR TITLE
Zipkin as option in Kubernetes

### PR DESCRIPTION
**Pull request by jasonrichardsmith**
This breaks Zipkin out as an option to deployment.
This also reduces the memory request for user.

Docs needs to be updated.

### CODE REVIEW

**Comment by mongrelion** [comment]
Nice to see this landing. I specially like the part where we reduce the memory requirements for The Shop.

A couple of things that I think you should take care of before getting this merged:

1. Can you squash the commits 7b894cfae555b1e7257971c865a2269528f146ad & 0754c2c3630b9d0c64f8a7fc4324eb48ee73ccb9? They seem to be doing the same thing so they might as well just be one commit.
2. The [`complete-demo.yaml`](https://github.com/microservices-demo/microservices-demo/blob/c5829292b2c7e428b612ff61cb7c14698787a089/deploy/kubernetes/complete-demo.yaml) file still defines zipkin. According to the requirements, Zipkin should be completely optional. Can you make sure you remove it from there as well?
3. @errordeveloper had already started some work towards this. PR #702 is the testimonial of that but obviously is not as thorough as this one. We need to make sure that we close that one once this gets merged.

For the rest it's looking good 👍

**Comment by jasonrichardsmith** [comment]
In response.
I will squash all when merged
@errordeveloper's work removed it from the complete demo I merged his branch into this one
I am consolidating both PRs under one
@mongrelion

**Comment by mongrelion** [comment]
:shipit:

**Review by mongrelion — APPROVED** [review]

**Comment by jasonrichardsmith** [comment]
This is waiting for this PR to be merged
https://github.com/microservices-demo/microservices-demo.github.io/pull/68

**Pull request merged**
