### PR TITLE
update grafana version

### PR DESCRIPTION
**Pull request by rodrmartinez**
Updates Grafana Deployment to the last image version

### CODE REVIEW

**Comment by elieserr** [comment]
A README will help to understand how to deploy grafana

**Comment by elieserr** [comment]
I was able to get grafana up and running, but Im not able to see any dashboard in the grafana instance, is that the desired outcome?

**Comment by elieserr** [comment]
I tried running the job to upload the script again and it works as expected! However, the dashboards are not showing any active metrics. 
Feel free to close this since the idea was to update the grafana deployment but please create a new issue so somebody can work on updating the dashboards.

**Review by elieserr — APPROVED** [review]
LGTM

**Comment by rodrmartinez** [comment]
> I was able to get grafana up and running, but Im not able to see any dashboard in the grafana instance, is that the desired outcome?

Grafana has to be in the running state before applying the `23-grafana-import-dash-batch.yaml ` manifest to import the dashboards

**Pull request merged**
